cookie = "ASP.NET_SessionId=ywvujrgpl1ndxoxuc12yxy01"

# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

### GetInfo

GET http://127.0.0.1:8000/info
Cookie: {{cookie}}
###

### AuthCode
POST http://127.0.0.1:8000/authcode
Content-Type: application/json

{
  "cookie": "ASP.NET_SessionId=ywvujrgpl1ndxoxuc12yxy01"
}

### getAreas
GET http://127.0.0.1:8000/selfhelp/areas
Content-Type: application/json
Cookie: {{cookie}}

### getHouses
GET http://127.0.0.1:8000/selfhelp/houses?area_id=001005
Cookie: {{cookie}}

### getRoom
GET  http://127.0.0.1:8000/selfhelp/rooms?area_id=001005&house_id=001005006
Cookie: {{cookie}}
