### AccBalance
GET http://10.14.0.124/zytk35portal/Cardholder/AccBalance.aspx
Accept: application/json
Cookie: ASP.NET_SessionId=j20bmrs2blx5gkcjkni1oltb
###

### Cardholder
GET http://10.14.0.124/zytk35portal/Cardholder/Cardholder.aspx
Accept: application/json
Cookie: ASP.NET_SessionId=j20bmrs2blx5gkcjkni1oltb
###


### main
GET http://10.14.0.124/zytk35portal/


### AuthCode
GET http://10.14.0.124/zytk35portal/AuthCode.aspx
Cookie: {{cookie}}
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9

### SelfHelp
GET http://10.14.0.124/zytk35portal/Cardholder/SelfHelp.aspx
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}

__EVENTTARGET=payButton


### get_house_list
POST {{selfUrl}}
Content-Type: text/plain
Cookie: {{cookie}}
X-AjaxPro-Method: GetHouseList

{"AreaId":"001005"}

### get_room_list
POST {{selfUrl}}
Content-Type: text/plain
Cookie: {{cookie}}
X-AjaxPro-Method: GetRoomList

{
  "areaId": "001005",
  "HouseId": "001005006"
}

### set_room_num
POST {{selfUrl}}
Content-Type: text/plain
Cookie: {{cookie}}
X-AjaxPro-Method: SetRoomNum

{
  "RoomId": "10-601"
}