{
 "title": "HNIU 电费监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "area",
    "label": "楼栋",
    "query": "from(bucket: \"hniu\")\n  |> range(start: 2023-02-11T22:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"area\")\n  |> drop(columns: [\"id\",])  \n  |> keep(columns: [\"_value\", \"id\"])  "
   },
   {
    "name": "floor",
    "label": "楼层",
    "query": "area=from(bucket: \"hniu\")\n  |> range(start: 2023-02-11T22:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"area\")\n  |> filter(fn: (r) => r[\"_value\"] == \"${area}\")\n  |> unique(column: \"_value\")\n  |> findRecord(fn: (key) => key._field == \"name\", idx: 0)\n\nfrom(bucket: \"hniu\")\n  |> range(start: 2023-02-11T22:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house\")\n  |> filter(fn: (r) => r[\"area_id\"] == area.id)\n  |> filter(fn: (r) => r[\"_field\"] == \"name\")\n  |> unique(column: \"_field\")\n  |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "${area} 电费信息",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "area=from(bucket: \"hniu\")\n  |> range(start: 2023-02-11T22:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"area\")\n  |> filter(fn: (r) => r[\"_value\"] == \"${area}\")\n  |> unique(column: \"_value\")\n  |> findRecord(fn: (key) => key._field == \"name\", idx: 0)\n  \n\nfrom(bucket: \"hniu\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"money\")\n  |> filter(fn: (r) => r[\"area_id\"] == area.id)\n  |> filter(fn: (r) => r[\"room_id\"] !~ /^WC.*/)\n  |> filter(fn: (r) => r[\"_value\"] >= -10.0)\n  |> group(columns: [\"_field\"])\n  |> fill(column: \"_value\", usePrevious: true)  \n  |> unique(column: \"room_id\")\n  |> sum(column: \"_value\")\n"
    },
    {
     "query": "area=from(bucket: \"hniu\")\n  |> range(start: 2023-02-11T22:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"area\")\n  |> filter(fn: (r) => r[\"_value\"] == \"${area}\")\n  |> unique(column: \"_value\")\n  |> findRecord(fn: (key) => key._field == \"name\", idx: 0)\n\nhouse=from(bucket: \"hniu\")\n  |> range(start: 2023-02-11T22:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house\")\n  |> filter(fn: (r) => r[\"area_id\"] == area.id)\n  |> filter(fn: (r) => r[\"_value\"] == \"${floor}\")\n  |> unique(column: \"id\")  \n  |> findRecord(fn: (key) => key._field == \"name\", idx: 0)  \n\nfrom(bucket: \"hniu\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"money\")\n  |> filter(fn: (r) => r[\"house_id\"] == house.id)\n  |> filter(fn: (r) => r[\"room_id\"] !~ /^WC.*/)\n  |> filter(fn: (r) => r[\"_value\"] >= -10.0)\n  |> fill(column: \"_value\", usePrevious: true)  \n  |> unique(column: \"room_id\")\n  |> group(columns: [\"_field\",\"_start\",\"_stop\"])\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "${floor} 电费总揽",
   "type": "stat",
   "gridPos": { "h": 11, "w": 17, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "area=from(bucket: \"hniu\")\n  |> range(start: 2023-02-11T22:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"area\")\n  |> filter(fn: (r) => r[\"_value\"] == \"${area}\")\n  |> unique(column: \"_value\")\n  |> findRecord(fn: (key) => key._field == \"name\", idx: 0)\n\nhouse=from(bucket: \"hniu\")\n  |> range(start: 2023-02-11T22:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house\")\n  |> filter(fn: (r) => r[\"area_id\"] == area.id)\n  |> filter(fn: (r) => r[\"_value\"] == \"${floor}\")\n  |> unique(column: \"id\")  \n  |> findRecord(fn: (key) => key._field == \"name\", idx: 0)  \n\nfrom(bucket: \"hniu\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"money\")\n  |> filter(fn: (r) => r[\"house_id\"] == house.id)\n  |> filter(fn: (r) => r[\"room_id\"] !~ /^WC.*/)\n  |> fill(column: \"_value\", usePrevious: true)  \n  |> unique(column: \"room_id\")\n  |> keep(columns: [\"_time\",\"room_id\",\"_value\"])\n"
    }
   ]
  },
  {
   "title": "${area} 欠费列表",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "area=from(bucket: \"hniu\")\n  |> range(start: 2023-02-11T22:00:00Z, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"area\")\n  |> filter(fn: (r) => r[\"_value\"] == \"${area}\")\n  |> unique(column: \"_value\")\n  |> findRecord(fn: (key) => key._field == \"name\", idx: 0)\n\nfrom(bucket: \"hniu\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"money\")\n  |> filter(fn: (r) => r[\"area_id\"] == area.id)\n  |> filter(fn: (r) => r[\"room_id\"] !~ /^WC.*/)\n  |> filter(fn: (r) => r[\"_value\"] < 0)\n  |> fill(column: \"_value\", usePrevious: true)  \n  |> unique(column: \"room_id\")\n  |> keep(columns: [\"_time\",\"room_id\",\"_value\"])\n"
    }
   ]
  }
 ]
}